### ISSUE TITLE
Openvpn bridge mode on r5638

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wl500g/wl500g#457]
```
The openvpn not correct running on 5638 firmware on RTN-16 router.
I have not any access to local resources after connection to openvpn.
I can connect to vpn server only.
Due to this I had to return r5066 firmware.

post-firewall part for openvpn:
iptables -A INPUT -p udp --dport 1195 -j ACCEPT
iptables -A FORWARD -i tap+ -j ACCEPT
iptables -A FORWARD -o tap+ -j ACCEPT

openvpn start-up script (part only):
br="br0"
tap="tap0"
if [ $1 = "start" ]; then
    openvpn --mktun --dev $tap
    brctl addif $br $tap
    ifconfig $tap 0.0.0.0 promisc up
fi
. /opt/etc/init.d/rc.func

Next issue (long time). Please can you return usbhid module to the firmware. I 
am not able to connect with my UPS.

Thank you

```

Original issue reported on code.google.com by `j...@seznam.cz` on 8 Nov 2014 at 10:03

**Comment by ondrej-bartos** [comment]
+1 openvpn daemon is impossible to stop is same on my device

can we get fixed kernel ? 

/tmp/syslog.log
Jan 18 14:10:09 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Jan 18 14:10:19 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Jan 18 14:10:29 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Jan 18 14:10:39 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Jan 18 14:10:49 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Jan 18 14:10:59 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Jan 18 14:11:10 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Jan 18 14:11:20 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Jan 18 14:11:30 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Jan 18 14:11:40 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1

**Comment by ondrej-bartos** [comment]
some new observations:
openvpn config in "topology subnet" on wl500gpv2 does not suffer from that problem, it looks only /30 config is impacted. /30 is deprecated anyway.

**Comment by themiron** [comment]
hi, does the same happen with tap interfaces?

**Comment by ondrej-bartos** [comment]
i cannot comment on this, i dont have tap interface configuration and don't have test environment for it, give a try

**Comment by themiron** [comment]
would be highly appreciated.
also, lease use up-to-date 7xxx fw versions from http://asus.vectormm.net/rtn/

**Comment by ondrej-bartos** [comment]
i also need and tested to access ssh, www and 8080 when openvpn is up (wl500 is client in my setup) but tcpdump shows that all packets ends at tun0 interface and dont go to br0.  i tried to apply iptables rules:

iptables -A FORWARD -i tap+ -j ACCEPT
iptables -A FORWARD -o tap+ -j ACCEPT

but they dont have any effect

**Comment by themiron** [comment]
fixed with fd432c697f079986a6e2f8adf911a57c73d69e64 as well
check out new autobuilds builds tomorrow at http://asus.vectormm.net/rtn/

**Comment by ondrej-bartos** [comment]
Looks the problem is not resolved:

`Sat Mar 26 11:24:19 2016 SENT CONTROL [techon.cz]: 'PUSH_REQUEST' (status=1)
Sat Mar 26 11:24:19 2016 PUSH: Received control message: 'PUSH_REPLY,route 192.168.1.0 255.255.255.224,route 192.168.4.0 255.255.255.224,topology subnet,tun-mtu 1200,route-gateway 192.168.3.1,topology subnet,ping 30,ping-restart 120,ifconfig 192.168.3.2 255.255.255.0'
Sat Mar 26 11:24:19 2016 Options error: option 'tun-mtu' cannot be used in this context ([PUSH-OPTIONS])
Sat Mar 26 11:24:19 2016 OPTIONS IMPORT: timers and/or timeouts modified
Sat Mar 26 11:24:19 2016 OPTIONS IMPORT: --ifconfig/up options modified
Sat Mar 26 11:24:19 2016 OPTIONS IMPORT: route options modified
Sat Mar 26 11:24:19 2016 OPTIONS IMPORT: route-related options modified
Sat Mar 26 11:24:19 2016 TUN/TAP device tun0 opened
Sat Mar 26 11:24:19 2016 TUN/TAP TX queue length set to 100
Sat Mar 26 11:24:19 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Sat Mar 26 11:24:19 2016 /sbin/ifconfig tun0 192.168.3.2 netmask 255.255.255.0 mtu 1200 broadcast 192.168.3.255
Sat Mar 26 11:24:19 2016 /sbin/route add -net 192.168.1.0 netmask 255.255.255.224 gw 192.168.3.1
Sat Mar 26 11:24:19 2016 /sbin/route add -net 192.168.4.0 netmask 255.255.255.224 gw 192.168.3.1
Sat Mar 26 11:24:19 2016 Initialization Sequence Completed

^C

Sat Mar 26 11:41:44 2016 event_wait : Interrupted system call (code=4)
Sat Mar 26 11:41:44 2016 /sbin/route del -net 192.168.4.0 netmask 255.255.255.224
Sat Mar 26 11:41:44 2016 /sbin/route del -net 192.168.1.0 netmask 255.255.255.224
Sat Mar 26 11:41:44 2016 Closing TUN/TAP interface
Sat Mar 26 11:41:44 2016 /sbin/ifconfig tun0 0.0.0.0`

syslog:

`tail /tmp/syslog.log 
Mar 26 11:46:06 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Mar 26 11:46:17 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Mar 26 11:46:27 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Mar 26 11:46:37 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Mar 26 11:46:47 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Mar 26 11:46:57 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Mar 26 11:47:07 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Mar 26 11:47:17 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Mar 26 11:47:27 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1
Mar 26 11:47:37 kernel: unregister_netdevice: waiting for tun0 to become free. Usage count = 1`

uname -a
Linux asus 2.6.22.21 #2 Sat Mar 26 02:25:34 MSK 2016 mips GNU/Linux

Using latest:  WL500gpv2-1.9.2.7-rtn-r7438M-g373b73c.trx

**Comment by dvglab** [comment]
The problem is in incorrect tun.c. Developers has backported a number of patches to tun.c to work with pseudo-socket object in tun.c, so the problem came with commt https://github.com/wl500g/wl500g/commit/d2195cd85cfc73b90a796911288846098f4126e3 I've revert this changes and build firmware with old version of tun.c. Everithing works like a charm. Download here:
https://drive.google.com/folderview?id=0B3siHuUeUYRBbk5CUXdwZmJLV0E&usp=sharing

**Comment by themiron** [comment]
fixed with d25101079fd09485c5d11f01090cbea3aaccaa9b
